# SECURITY NOTICE:
# - All secrets must be stored in GitHub Secrets/GitLab CI Variables
# - Never commit credentials to version control
# - Use ${{ secrets.SECRET_NAME }} syntax for sensitive values
# - Enable secret scanning in repository settings

name: Quantis CI/CD

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]

jobs:
  api-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f api/requirements.txt ]; then pip install -r api/requirements.txt; fi

      - name: Run tests
        run: |
          cd api
          python -m pytest

  frontend-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: |
          cd frontend
          npm ci

      - name: Run tests
        run: |
          cd frontend
          npm test

  model-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f models/requirements.txt ]; then pip install -r models/requirements.txt; fi

      - name: Run model tests
        run: |
          cd models
          python -m pytest

  docker-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Frontend Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: false
          tags: quantis-frontend:latest

  build-and-deploy:
    needs: [api-test, frontend-test, model-test, docker-build]
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Build frontend
        run: |
          cd frontend
          npm ci
          npm run build

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install API dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f api/requirements.txt ]; then pip install -r api/requirements.txt; fi

    # Add deployment steps here based on your deployment strategy
