---
- name: Configure web servers
  hosts: webservers
  become: true
  gather_facts: true
  vars_files:
    - "{{ playbook_dir }}/../group_vars/all.yml"
  roles:
    - common
    - webserver

- name: Configure database servers
  hosts: databases
  become: true
  gather_facts: true
  vars_files:
    - "{{ playbook_dir }}/../group_vars/all.yml"
  roles:
    - common
    - database
