apiVersion: v1
kind: Service
metadata:
  name: quantis-redis
  labels:
    app: quantis-redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: redis
  selector:
    app: quantis-redis
